<a href="https://colab.research.google.com/github/Raj1192/Machine_Learning_Projects/blob/main/Breast_Cancer_Prediction/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
string=tf.Variable("Hello",tf.string)
print(string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Hello'>


In [ ]:
number=tf.Variable(324,tf.int16)
print(number)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>


In [ ]:
floating=tf.Variable(3.14,tf.float64)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.14>


Rank 0 and Rank 1 Tensor

In [ ]:
rank1_tensor=tf.Variable(['x','y','z'],tf.string)
rank2_tensor=tf.Variable([['x','y','z'],['a','b','c']],tf.string)
rank3_tensor=tf.Variable([['x','y','z'],['a','b','c'],['1','2','3']],tf.string)

To determine the rank of tensor

In [ ]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tf.rank(rank3_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

Shape of Tensor

In [ ]:
rank1_tensor.shape

TensorShape([3])

In [ ]:
rank2_tensor.shape

TensorShape([2, 3])

In [ ]:
rank3_tensor.shape

TensorShape([3, 3])

Reshape the Tensor

In [ ]:
t1=tf.ones([1,2,3])
print(t1)
t2=tf.reshape(t1,[2,3,1])
print(t2)
t3=tf.reshape(t1,[3,-1])
print(t3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
t4=tf.zeros([5,5,1,1])
print(t4)

tf.Tensor(
[[[[0.]]

  [[0.]]

  [[0.]]

  [[0.]]

  [[0.]]]


 [[[0.]]

  [[0.]]

  [[0.]]

  [[0.]]

  [[0.]]]


 [[[0.]]

  [[0.]]

  [[0.]]

  [[0.]]

  [[0.]]]


 [[[0.]]

  [[0.]]

  [[0.]]

  [[0.]]

  [[0.]]]


 [[[0.]]

  [[0.]]

  [[0.]]

  [[0.]]

  [[0.]]]], shape=(5, 5, 1, 1), dtype=float32)
